title: APCS Website
author: Sarthak Roongta
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website with facts all about me, for my final project in A.P. Computer Science A!
# social links
twitter_username: Sarthakr1 # DO NOT include the @ character, or else the build will fail!
github_username:  SarthakRoongta # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: slate
